name: Upload Scan Results

description: Upload scan results to DefectDojo

runs:
  using: "composite"
  steps:
    - name: Upload Scan Results
      run: |
        for file in checkov-results.json nuclei-results.txt gitleaks-report.json trivy-results.json dependency-check-report.xml bearer-results.json; do
          scan_type=$(echo "$file" | sed 's/-results.*//g' | sed 's/.json//g' | sed 's/.txt//g' | sed 's/.xml//g' | tr '-' ' ' | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
          echo "Uploading $file as $scan_type Scan"
          response=$(curl -X POST "http://18.220.221.176:8080/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Content-Type: multipart/form-data" \
            -F "scan_type=$scan_type Scan" \
            -F "product_name=DevSecOps" \
            -F "file=@results/$file")
          echo "Response: $response"
          if [[ "$response" == *"error"* ]]; then
            echo "❌ Error al subir $file a DefectDojo."
            exit 1
          fi
        done
      shell: bash
