name: Bearer SAST Scan

description: Run Bearer for Static Application Security Testing

runs:
  using: "composite"
  steps:
    - name: Run Bearer
      uses: bearer/bearer-action@v2
      with:
        output: results/bearer-results.json
      continue-on-error: true
