name: Checkov IaC Scan

description: Run Checkov to scan infrastructure as code

runs:
  using: "composite"
  steps:
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        output_format: json
        output_file_path: results/checkov-results.json
      continue-on-error: true
