name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Results Directory
        run: |
          mkdir -p results
          chmod -R 777 results

      - name: Install Dependencies
        run: bash .github/workflows/steps/setup-dependencies.sh

      - name: Run Gitleaks (Secret Scan)
        run: bash .github/workflows/steps/security-scan/gitleaks-scan.sh

      - name: Run Checkov (IaC Scan)
        run: bash .github/workflows/steps/security-scan/checkov-scan.sh

      - name: Run Nuclei (DAST Scan)
        run: bash .github/workflows/steps/security-scan/nuclei-scan.sh

      - name: Run Trivy (Container Scan)
        run: bash .github/workflows/steps/security-scan/trivy-scan.sh

      - name: Run Dependency Check (SCA)
        run: bash .github/workflows/steps/security-scan/dependency-check.sh

      - name: Run Bearer (SAST Scan)
        run: bash .github/workflows/steps/security-scan/bearer-scan.sh

      - name: Upload Scan Results to DefectDojo
        run: bash .github/workflows/steps/upload-results.sh ${{ secrets.DEFECTDOJO_API_KEY }} ${{ env.ENGAGEMENT_NAME }} ${{ env.PRODUCT_NAME }} ${{ env.DEFECTDOJO_URL }}

