name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Results Directory
        run: mkdir -p results

      - name: Run Checkov (IaC Scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          output_format: json
          output_file_path: results/checkov-results.json
        continue-on-error: true

      - name: Verify Checkov Execution
        run: |
          if [ ! -s results/checkov-results.json ]; then
            echo "❌ Error: El archivo checkov-results.json no existe o está vacío."
            exit 1
          else
            echo "✅ Archivo encontrado, procediendo con la carga."
          fi

      - name: Verificar conexión con DefectDojo
        run: |
          curl -X GET "http://3.135.211.4:8080/api/v2/engagements/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json"

      - name: Upload Checkov Report to DefectDojo
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_API_KEY }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          file: results/checkov-results.json
          scan_type: Checkov Scan
          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
