name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Results Directory
        run: mkdir -p results

      - name: Run Checkov (IaC Scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          output_format: json
          output_file_path: results/checkov-results.json
        continue-on-error: true

      - name: Run Gitleaks (Secret Scan)
        uses: gitleaks/gitleaks-action@v2.3.7
        with:
          config: .gitleaks.toml
          report-format: json
          report-path: results/gitleaks-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Upload Checkov Report to DefectDojo
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_API_KEY }}
          defectdojo_url: "http://3.135.211.4:8080"
          file: results/checkov-results.json
          scan_type: Checkov Scan
          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        continue-on-error: true

      - name: Upload Gitleaks Report to DefectDojo
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_API_KEY }}
          defectdojo_url: "http://3.135.211.4:8080"
          file: results/gitleaks-report.json
          scan_type: Gitleaks Scan
          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        continue-on-error: true
