name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Results Directory
        run: .github/workflows/steps/prepare-results-directory.yml

      - name: Install Dependencies
        run: .github/workflows/steps/setup-dependencies.yml

      - name: Run Gitleaks (Secret Scan)
        run: .github/workflows/steps/security-scans/gitleaks-scan.yml

      - name: Run Checkov (IaC Scan)
        run: .github/workflows/steps/security-scans/checkov-scan.yml

      - name: Run Nuclei (DAST Scan)
        run: .github/workflows/steps/security-scans/nuclei-scan.yml

      - name: Run Trivy (Container Scan)
        run: .github/workflows/steps/security-scans/trivy-scan.yml

      - name: Run Dependency Check (SCA)
        run: .github/workflows/steps/security-scans/dependency-check.yml

      - name: Run Bearer (SAST Scan)
        run: .github/workflows/steps/security-scans/bearer-scan.yml

      - name: Upload Scan Results to DefectDojo
        run: .github/workflows/steps/upload-results.yml
